; PlatformIO Project Configuration File
[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 115200
lib_deps =
	adafruit/Adafruit NeoPixel@^1.12.3
	adafruit/Adafruit Unified Sensor
	arduino-libraries/Servo@^1.2.1
	arduinogetstarted/ezButton@^1.0.6
	robtillaart/AS5600@^0.6.5
build_flags = -w -Wno-unknown-pragmas
