; PlatformIO Project Configuration File
[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 115200
lib_deps =
	jrowberg/I2Cdevlib-MPU6050
build_flags = -w -Wno-unknown-pragmas
