; PlatformIO Project Configuration File
[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 115200
lib_deps =
	arduino-libraries/Servo@^1.2.1
	mathertel/OneButton@^2.6.1
	sparkfun/SparkFun TB6612FNG Motor Driver Library@^1.0.0
build_flags = -w -Wno-unknown-pragmas
