; PlatformIO Project Configuration File
[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 115200
lib_deps =
	sparkfun/SparkFun TB6612FNG Motor Driver Library@^1.0.0
	z3t0/IRremote@^4.5.0
build_flags = -w -Wno-unknown-pragmas
